1.	Create a python program to find duplicate files by content. User will input path and it will scan all directories, sub-directories to find all duplicates files.
Delete the found duplicate file.


In [2]:
# Importing Libraries
import os
from pathlib import Path
from filecmp import cmp


# list of all documents
DATA_DIR = Path("C:/Users/dkholiya/practice")
files = sorted(os.listdir(DATA_DIR))

# List having the classes of documents
# with the same content
duplicateFiles = []

# comparison of the documents
for file_x in files:

    if_dupl = False

    for class_ in duplicateFiles:
        # Comparing files having same content using cmp()
        # class_[0] represents a class having same content
        if_dupl = cmp(
            DATA_DIR / file_x,
            DATA_DIR / class_[0],
            shallow=False
        )
        if if_dupl:
            class_.append(file_x)
            break

    if not if_dupl:
        duplicateFiles.append([file_x])

# Print results
print(duplicateFiles)


[['constitution.txt'], ['s1.sql'], ['test.txt', 'test1.txt', 'test2.txt'], ['test4.txt']]


In [10]:
for i in duplicateFiles:
    if len(i)>1:
        del i[1:]
print(duplicateFiles)

[['constitution.txt'], ['s1.sql'], ['test.txt'], ['test4.txt']]


2.	Generate random Password with exact length = 6, with minimum 1 uppercase, 2 lowercase, 2 digits, and remaining special characters.
Using these packages [random, strings]


In [12]:
import random
import string

upper=1
lower=2
digits=2
special=1

uc_pool=string.ascii_uppercase
l_pool=string.ascii_lowercase
d_pool=string.digits
sp_pool=string.punctuation

all_pool=uc_pool+l_pool+d_pool+sp_pool
password=''.join(random.sample(all_pool,6))

while(
    sum(1 for c in password if c in uc_pool)<upper or
    sum(1 for c in password if c in l_pool)<lower or
    sum(1 for c in password if c in d_pool)<digits or
    sum(1 for c in password if c in sp_pool)<special
):
    password=''.join(random.sample(all_pool,6))

print(password)

    


67Kl-u


3.	Create 2D array and update the same 2D array provided that every prime number position should be replaced by cube of the positioned number.

In [17]:
import numpy as np
size=5
arr1= np.zeros((size,size),dtype=np.int32)
def is_prime(n):
    if n<2:
        return False
    for i in range(2,int(n**0.5)+1):
        if n%i==0:
            return False
    return True

for i in range(size):
    for j in range(size):
        if is_prime(i*size+j):
            arr1[i,j]=(i*size+j)**3
print(arr1)

[[    0     0     8    27     0]
 [  125     0   343     0     0]
 [    0  1331     0  2197     0]
 [    0     0  4913     0  6859]
 [    0     0     0 12167     0]]


4.	Python program to get the sum of every cubed value and its previous integer. 

In [4]:
import math

# Create a 2D array with dimensions 5 x 5
array_2d = [[0 for x in range(5)] for y in range(5)]

# Iterate over the array and update prime number positions
prime_cubes_sum = 0
for i in range(5):
    for j in range(5):
        # Get the value at the current position
        value = (i * 5) + j + 1
        
        # Check if the value is prime
        is_prime = True
        for k in range(2, int(math.sqrt(value)) + 1):
            if value % k == 0:
                is_prime = False
                break
        
        # If the value is prime, update the position with its cube
        if is_prime:
            cube = value ** 3
            prime_cubes_sum += cube + (value - 1)
            array_2d[i][j] = cube

# Print the updated array and the sum of prime cubes and their previous integers
for row in array_2d:
    print(row)
print("Sum of prime cubes and their previous integers:", prime_cubes_sum)

[1, 8, 27, 0, 125]
[0, 343, 0, 0, 0]
[1331, 0, 2197, 0, 0]
[0, 4913, 0, 6859, 0]
[0, 0, 12167, 0, 0]
Sum of prime cubes and their previous integers: 28062


5.	Given two arrays, find their intersection. Examples:

Input:  arr1[] = [1, 3, 4, 5, 7]
             arr2[] = [2, 3, 5, 6]


In [26]:
arr1=[1,3,4,5,7]
arr2=[2,3,5,6]
result = list(filter(lambda x: x in arr1, arr2))
print(result)

[3, 5]


6.	Create a 7 x 7  2D array having only multiples of 7. And return the last element of the same.

In [8]:
import pandas as pd
ar= [ [0]*7 for i in range(7)]
for i in range(7):
    for j in range(7):
        ar[i][j]=7*(i+1)*(j+1)

print(ar) 

l=ar[-1][-1]
print("last element is :" ,l)


[[7, 14, 21, 28, 35, 42, 49], [14, 28, 42, 56, 70, 84, 98], [21, 42, 63, 84, 105, 126, 147], [28, 56, 84, 112, 140, 168, 196], [35, 70, 105, 140, 175, 210, 245], [42, 84, 126, 168, 210, 252, 294], [49, 98, 147, 196, 245, 294, 343]]
last element is : 343


7.	Checker Board Patten using Numpy:
[   1   0   1   0   1   0   1
    0   1   0   1   0   1   0
    1   0   1   0   1   0   1
    0   1   0   1   0   1   0
    1   0   1   0   1   0   1  ]


In [78]:
import numpy as np
x = np.ones((7, 5))
x[1:-1, 1:-1] = 0
print(x)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


8.	Create a given Matrix:
[  A,     B,     C,       D
   E,      F,     G,       H
    I,      a,      K,       L
   M,    N,     o,       P
   Q,     R,      S,       T
   U,     0,     W,      O ]

Replace all the vowels by np.nan
A, E, I, O U  -- >  np.nan
Return the count of the missing values


In [11]:
import numpy as np
arr_6=list("ABCDEFGHIJKLMNOPQRSTUVWX")
arr_7=list("AEIOU")
# arr_6.reshape(4,6)
# arr_7
j=0
for i in range(0,len(arr_6)):
    if j<len(arr_7) and arr_6[i]==arr_7[j]:
        j+=1
        arr_6[i]=np.nan 

arr_6

[nan,
 'B',
 'C',
 'D',
 nan,
 'F',
 'G',
 'H',
 nan,
 'J',
 'K',
 'L',
 'M',
 'N',
 nan,
 'P',
 'Q',
 'R',
 'S',
 'T',
 nan,
 'V',
 'W',
 'X']

In [12]:
arr_6=np.array(arr_6)
arr_6=list(arr_6)
# arr_6=arr_6.reshape(4,6)
arr_6

count=0
for i in arr_6:
    if i=='nan':
        count += 1
count



5